import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

/**
 * Configuração da fonte sans-serif Geist.
 */
const geistSans = Geist({
  variable: "--font-geist-sans", // Variável CSS para uso no Tailwind ou CSS global
  subsets: ["latin"],            // Subconjunto de caracteres carregados
});

/**
 * Configuração da fonte monoespaçada Geist Mono.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadados globais da aplicação.
 *
 * Utilizados pelo Next.js para:
 * • SEO (Search Engine Optimization)
 * • Título exibido na aba do navegador
 * • Descrição para mecanismos de busca
 * • Compartilhamento em redes sociais
 */
export const metadata: Metadata = {
  title: "Contar-IA",
  description: "Generated by the Storytellers Team",
};

/**
 * Layout raiz da aplicação (Root Layout).
 *
 * Responsabilidades:
 * • Definir a estrutura HTML base de todas as páginas
 * • Aplicar estilos globais e fontes
 * • Envolver a aplicação com Providers globais (Context API)
 * • Configurar idioma do documento
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}   /* Aplica fonte principal */
          ${geistMono.variable}   /* Aplica fonte monoespaçada */
          antialiased             /* Suavização de fontes */
        `}
      >
        {/* ============================================================
           Providers globais da aplicação
           
           Inclui:
           • React Query (cache e requisições)
           • Contexto de sessão/autenticação
           • Contexto de histórias
           • Outros estados globais necessários
        ============================================================ */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
